project:
  type: website
  output-dir: docs
  
website:
  page-navigation: true
  title: "Jinglin Zhang"
  site-url: https://ISLab.github.io
  favicon: images/shandong.jpeg
  repo-url: https://github.com/zhoutao-sdu2025/ISLab.github.io
  navbar: 
    background: "#A9CCE3"
    search: true
    right: 
      - text: "Home"
        href: index.qmd
      - text: "Group"
        href: Group.qmd 
      - text: "Publications"
        href: publications.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Member"
        href: member.qmd
      - text: "Contact"
        href: contact.qmd
      - text: "中文"
        href: Chinese.qmd

format:
  html:
    theme: styles.scss
    toc: true            # 启用目录
    toc-position: right  # 将目录放置在页面的右侧
    toc-depth: 3         # 设置目录的深度，数字越大，目录越详细