::: {#center}
<!-- 自定义样式 -->
<style>
/* 容器设置 */
#center {
  max-width: 900px;
  margin: 0 auto;
  padding: 0 20px;
  box-sizing: border-box;
}

/* 文本排版优化 */
#center p, 
#center ul, 
#center ol, 
#center h2, 
#center h3 {
  text-align: justify;
  text-justify: inter-ideograph;
  word-break: break-word;
  line-height: 1.6;
}

</style>

## 期刊论文

1.  Wang Jiashu, Song Jinze, Zhang Hao, Zhang Zekai, Ji Yunlong, Zhang, Wenyin, **Zhang Jinglin** and Wang Xing, SPMNet: A Siamese Pyramid Mamba Network for Very-High-Resolution Remote Sensing Change Detection, **IEEE Transactions on Geoscience and Remote Sensing**, 2025, [-Link-](DOI:10.1109/TGRS.2025.3565801). （中科院一区，IF:5.855）
2.  S. Wang, Y.B. Gao, S. Li, C. Lv, X. Cai, C.K. Li, H. Yuan, **J.L. Zhang**, MetricGrids: Arbitrary Nonlinear Approximation with Elementary Metric Grids based Implicit Neural Representation. **IEEE Conference on Computer Vision and Pattern Recognition (CVPR)**, 2025, Highlight Paper.
3.  Z. Zhang, Q. Chen, M. Xiong, S. Ding, Z. Su, X. Yao, Y. Sun, C. Bai, and **J. Zhang**, Zero-shot learning in industrial scenarios: New large-scale benchmark, challenges and baseline, **Proceedings of the AAAI Conference on Artificial Intelligence(AAAI)**, 2025.
4.  Ding S, Xiong M, Wang X, and Zhang J\*, Dynamic feature and context enhancement network for faster detection of small objects, **Expert Systems With Applications**, 2025, [-Link-](DOI:10.1016/j.eswa.2024.125732).（中科院一区，IF:7.5）
5.  Yuanjiang Li, Liping Li, Lei Li, Xinyu Huang, Guodong Sun, Yina Wang, **Jinglin Zhang**, Research on Hybrid Data-Driven Method for Predicting the Remaining Useful Life of Lithium-Ion Batteries, **Computer Physics Communications**, 2025, [-Link-](https://doi.org/10.1016/j.cpc.2025.109500).（中科院二区，IF:7.2）
6.  Xiangjun Cai, Dagang Li, **Jinglin Zhang**, Zhuohao Wu, MA-EMD: Aligned empirical decomposition for multivariate time-series forecasting, **Expert Systems with Applications**, 2025, [-Link-](https://doi.org/10.1016/j.eswa.2024.126080).（中科院一区，IF:7.5）
7.  **Zhang J**, Zhang Z, Chen Q et al, Representation Learning Based on Co-Evolutionary Combined With Probability Distribution Optimization for Precise Defect Location, **IEEE Transactions on Neural Networks and Learning Systems** 2024,[-Link-](DOI:10.1109/TNNLS.2024.3479734). （中科院一区，IF:10.4）
8.  Zhu, Pengfei and Li, Jialu and Wang, Yu and Xiao, Bin and **Zhang, Jinglin** and Lin, Wanyu and Hu, Qinghua, Boosting Pseudo-Labeling With Curriculum Self-Reflection for Attributed Graph Clustering, **IEEE Transactions on Neural Networks and Learning Systems**, 2025,36(5),pp:8346-8359, [-Link-](DOI:10.1109/TNNLS.2024.3416167).（中科院一区，IF:10.4）
9.  Lei Li, Yuanjiang Li, Runze Mao, Yueling Li, Weizhi Lu, **Jinglin Zhang**, TPANet: A novel triple parallel attention network approach for remaining useful life prediction of lithium-ion batteries, **Energy**, 2024, [-Link-](https://doi.org/10.1016/j.energy.2024.132890). （中科院一区，IF:9.0）
10. Qinghui Chen, Lunqian Wang, Zekai Zhang, Xinghua Wang, Weilin Liu, Bo Xia, Hao Ding, **Jinglin Zhang**, Sen Xu and Xin Wang, Dual-path aggregation transformer network for super-resolution with images occlusions and variability, **Engineering Applications of Artificial Intelligence**, 2025, [-Link-](https://doi.org/10.1016/j.engappai.2024.109535). （中科院一区，IF:7.5）
11. Song, Y., Wang, X., Yao, J. and **Zhang J**. ViTGaze: gaze following with interaction features in vision transformers. **Vis. Intell**, 2:31,2024, [-Link-](https://doi.org/10.1007/s44267-024-00064-9).
12. Ding H, Xia B, Liu W, Zhang Z, **Zhang J**, Wang X, Xu S, A Novel Mamba Architecture with a Semantic Transformer for Efficient Real-Time Remote Sensing Semantic Segmentation. **Remote Sensing**, 2024, 16(14):2620. [-Link-](https://doi.org/10.3390/rs1614262). （中科院二区，IF:4.2）
13. Lunqian Wang, Xinghua Wang, Weilin Liu, Hao Ding, Bo Xia, Zekai Zhang, **Jinglin Zhang** and Sen Xu, A unified architecture for super-resolution and segmentation of remote sensing images based on similarity feature fusion, **Displays**, 2024, [-Link-](https://doi.org/10.1016/j.displa.2024.102800). （中科院二区，IF:3.7）
14. Yuanjiang Li, Ying Zhu, Yang Yu, Runze Mao, Linchang Ye, Yun Liu, Ruochen Liu, Tao Lang and **Jinglin Zhang**, DACA: A domain adaptive fault diagnosis approach with class-aware based on cross-domain extreme imbalance data, **Expert Systems with Applications**, 2024,[-Link-](https://doi.org/10.1016/j.eswa.2024.124944). （中科院一区，IF:7.5）
15. Shuxin Zhuang, Heye Zhang, Wanli Ding, Zhemin Zhuang, **Jinglin Zhang**, Zhifan Gao, Semi-supervised domain adaptation incorporating three-way decision for multi-view echocardiographic sequence segmentation, **Applied Soft Computing**, 2024, [-Link-](https://doi.org/10.1016/j.asoc.2024.111449). （中科院一区，IF:8.7）
16. H. Yan，Pan Mu，Cheng Huang，**J. Zhang** and C. Bai, Phy-CoCo: Physical Constraint-Based Correlation Learning for Tropical Cyclone Intensity and Size Estimation，**ECAI 2024**，pp. 2226-2233, [-Link-](DOI:10.3233/FAIA240744).
17. D. Zhao, Q. Wang\*, **J. Zhang** and C. Bai, Mine Diversified Contents of Multispectral Cloud Images Along With Geographical Information for Multilabel Classification, **IEEE Transactions on Geoscience and Remote Sensing**, 2023, vol. 61, pp. 1-15, [-Link-](DOI:10.1109/TGRS.2023.3270204). （中科院一区，IF:5.855）
18. Yang, D., He, X., Wang, J., Yu, G., Domeniconi, C. and **Zhang, J**. Federated Causality Learning with Explainable Adaptive Optimization. **AAAI 2024**, 38(15), 16308-16315.
19. Shang, S., Shan, Z., Liu, G., Wang, L., Wang, X., Zhang, Z. and **Zhang, J**. ResDiff: Combining CNN and Diffusion Model for Image Super-resolution. **AAAI 2024**, 38(8), 8975-8983.
20. S. Shang, **Zhang J**, X. Wang, X. Wang, Y. Li and Y. Li, Faster and Lighter Meteorological Satellite Image Classification by a Lightweight Channel-Dilation-Concatenation Net, **IEEE Journal of Selected Topics in Applied Earth Observations and Remote Sensing**, 2023, vol. 16: pp. 2301-2317, [-Link-](DOI:10.1109/JSTARS.2023.3243915).（中科院二区，IF:4.715）
21. C. Bai, Z. Cai, X. Yin and **J. Zhang**, LSDSSIMR: Large-Scale Dust Storm Database Based on Satellite Images and Meteorological Reanalysis Data, **IEEE Journal of Selected Topics in Applied Earth Observations and Remote Sensing**, vol. 16, pp. 10121-10131, 2023, [-Link-](doi:10.1109/JSTARS.2023.3325783). （中科院二区，IF:4.715）
22. Li Yuanjun, Zhu Zhiyu, Li Yuanjiang, **Zhang Jinglin**, Li Xi, Shang Shuyao and Zhu Dewen, CTMU-Net: An Improved U-Net for Semantic Segmentation of Remote-Sensing Images Based on the Combined Attention Mechanism, **IEEE Journal of Selected Topics in Applied Earth Observations and Remote Sensing**, vol.16, pp:10148-10161, 2023, [-Link-](10.1109/JSTARS.2023.3326960). （中科院二区，IF:4.715）
23. C. Huang, C. Bai, S. Chan, **J. Zhang**, and Y. Wu, MGTCF: Multi-Generator Tropical Cyclone Forecasting with Heterogeneous Meteorological Data, **AAAI, 2023**, vol. 37, no. 4, pp. 5096-5104.
24. Kang, X., Yu, G., Wang, J., Guo, W., Domeniconi, C. and **Zhang, J**. Incentive-Boosted Federated Crowdsourcing. **AAAI 2023**, 37(5), 6021-6029.
25. Gao, Z., Wang, J., Yu, G., Yan, Z., Domeniconi, C. and **Zhang, J**. Long-Tail Cross Modal Hashing. **AAAI 2023**, 37(6), 7642-7650.
26. L. -Q. Wang, X. -H. Wang, W. -L. Liu, B. Xia, H. Ding and **J. -L. Zhang**, Metafoemer Super-Resolution Network with Recursive Gated Attention for the Meteorological Satellite Cloud Image, **ICMLC 2023**, pp.528-535, [-Link-](doi:10.1109/ICMLC58545.2023.10327984).
27. Dong Zhang, Heye Zhang, Hongwei Zhang, Lei Xu, **Jinglin Zhang**, Zhifan Gao, Distance transform learning for structural and functional analysis of coronary artery from dual-view angiography, **Future Generation Computer Systems**, 2023(145): Pages 136-149, [-Link-](DOI:10.1016/j.future.2023.03.007). （中科院一区，IF:7.307）
28. L. Li, Y. Li, R. Mao, L. Li, W. Hua and **Zhang J**, Remaining useful life prediction for lithium-ion batteries with a hybrid model based on TCN-GRU-DNN and dual attention mechanism, **IEEE Transactions on Transportation Electrification**, [-Link-](DOI:10.1109/TTE.2023.3247614).（中科院一区，IF:6.520）
29. Zhifan Gao, Saidi Guo, Chenchu Xu, **Jinglin Zhang**, Mingming Gong, Javier Del Ser and Shuo Li, Multi-domain Adversarial Variational Bayesian Inference for Domain Generalization, **IEEE Transactions on Circuits and Systems for Video Technology**, 2022, [-Link-](DOI:10.1109/TCSVT.2022.3232112). （中科院一区，IF:5.859）
30. Jia Z, Yang S, **Zhang J**, Zhang Y, Yang Z, Xue K, Bai C. PRSOT: Precipitation Retrieval from Satellite Observations Based on Transformer. **Atmosphere**. 2022; 13(12):2048. [-Link-](https://doi.org/10.3390/atmos13122048).（中科院三区，IF:3.110）
31. Boyan Wang, Xuegang Hu, **Jinglin Zhang**, Chenchu Xu and Zhifan Gao, Intelligent Internet of Things in Mammography Screening using Multicenter Transformation Between Unified Capsules, **IEEE IoT Journal**, [-Link-](DOI:10.1109/JIOT.2022.3209895).（中科院一区，IF:9.936）
32. Pengfei Zhu, Zhilin Zhu, Yu Wang, **Jinglin Zhang**, Shuai Zhao, Multi-granularity episodic contrastive learning for few-shot learning. **Pattern Recognition**, 2022, 131, [-Link-](https://doi.org/10.1016/j.patcog.2022.108820).
33. Cong Bai, Dongxiaoyuan Zhao, Minjing Zhang and **Jinglin Zhang**, Multimodal Information Fusion for Weather Systems and Clouds Identification From Satellite Images, **IEEE Journal of Selected Topics in Applied Earth Observations and Remote Sensing**, 2022, 15, [-Link-](DOI:10.1109/JSTARS.2022.3202246).（中科院三区，IF:4.715）
34. F. Sun, C. Bai, Y. Song and **Zhang J**, MMINR: Multi-frame-to-Multi-frame Inference with Noise Resistance for Precipitation Nowcasting with Radar, **26th International Conference on Pattern Recognition (ICPR)**, Montreal, QC, Canada, 2022, pp. 97-103, [-Link-](DOI:10.1109/ICPR56361.2022.9956046).
35. Cong Bai, Chao Zeng, Qing Ma and **Jinglin Zhang**, Graph Convolutional Network Discrete Hashing for Cross-Modal Retrieval, **IEEE Transactions on Neural Networks and Learning Systems**, [-Link-](DOI:10.1109/TNNLS.2022.3174970). （中科院一区，IF:10.451）
36. Cheng huang, Cong Bai, Sixian Chan, and Jinglin **Zhang**, MMSTN: a Multi-Modal Spatial-Temporal Network for Tropical Cyclone Short-Term Prediction, **Geophysical Research Letters**, [-Link-](DOI:%2010.1029/2021GL096898). （中科院一区，IF:4.497）
37. Cong Bai, Feng Sun, **Jinglin Zhang**, Shengyong Chen, Rainformer: Features Extraction Balanced Network for Radar-based Precipitation Nowcasting, **IEEE Geoscience and Remote Sensing Letters**, [-Link-](DOI:%2010.1109/LGRS.2022.3162882). （中科院二区，IF:3.966）
38. Yuanjiang Li, Yunfeng Chen, Kai Zhu, Cong Bai and **Jinglin Zhang**, An Effective Federated Learning Verification Strategy and Its Applications for Fault Diagnosis in Industrial IoT Systems, Pages:16835-16849, 9(18), 2022, **IEEE IoT Journal**, [-Link-](DOI:%2010.1109/JIOT.2022.3153343).（中科院一区，IF:9.936）
39. Minmin Miao, Wenjun Hu, Baoguo Xu, **Jinglin Zhang**, Joel J. P. C. Rodrigues and Victor Hugo C. de Albuquerque, Automated CCA-MWF algorithm for unsupervised identification and removal of EOG artifacts from EEG, **Journal of Biomedical and Health Informatics**, Pages: 3607-3617, 26(8), 2022, [-Link-](DOI:10.1109/JBHI.2021.3131186).（中科院一区，IF:5.223）
40. 更多论文请查看中文简介

:::